### POST ngram_times data to Flask
POST http://127.0.0.1:5000/receive-json
Content-Type: application/json

{
  "ngram_times": {
    "[<shift>]->[<t>]": [
      186
    ],
    "[<t>]->[<h>]": [
      126,
      173
    ],
    "[<shift><t>]->[<h>]": [
      126
    ],
    "[<h>]->[<i>]": [
      208
    ],
    "[<t><h>]->[<i>]": [
      208
    ],
    "[<shift><t><h>]->[<i>]": [
      208
    ],
    "[<i>]->[<s>]": [
      135,
      256
    ],
    "[<h><i>]->[<s>]": [
      135
    ],
    "[<t><h><i>]->[<s>]": [
      135
    ],
    "[<shift><t><h><i>]->[<s>]": [
      135
    ],
    "[<s>]->[<space>]": [
      86,
      4,
      229
    ],
    "[<i><s>]->[<space>]": [
      86,
      4
    ],
    "[<h><i><s>]->[<space>]": [
      86
    ],
    "[<t><h><i><s>]->[<space>]": [
      86
    ],
    "[<shift><t><h><i><s>]->[<space>]": [
      86
    ],
    "[<space>]->[<i>]": [
      213
    ],
    "[<s><space>]->[<i>]": [
      213
    ],
    "[<i><s><space>]->[<i>]": [
      213
    ],
    "[<h><i><s><space>]->[<i>]": [
      213
    ],
    "[<t><h><i><s><space>]->[<i>]": [
      213
    ],
    "[<space><i>]->[<s>]": [
      256
    ],
    "[<s><space><i>]->[<s>]": [
      256
    ],
    "[<i><s><space><i>]->[<s>]": [
      256
    ],
    "[<h><i><s><space><i>]->[<s>]": [
      256
    ],
    "[<space><i><s>]->[<space>]": [
      4
    ],
    "[<s><space><i><s>]->[<space>]": [
      4
    ],
    "[<i><s><space><i><s>]->[<space>]": [
      4
    ],
    "[<space>]->[<a>]": [
      254
    ],
    "[<s><space>]->[<a>]": [
      254
    ],
    "[<i><s><space>]->[<a>]": [
      254
    ],
    "[<space><i><s><space>]->[<a>]": [
      254
    ],
    "[<s><space><i><s><space>]->[<a>]": [
      254
    ],
    "[<a>]->[<n>]": [
      157
    ],
    "[<space><a>]->[<n>]": [
      157
    ],
    "[<s><space><a>]->[<n>]": [
      157
    ],
    "[<i><s><space><a>]->[<n>]": [
      157
    ],
    "[<space><i><s><space><a>]->[<n>]": [
      157
    ],
    "[<n>]->[<o>]": [
      194
    ],
    "[<a><n>]->[<o>]": [
      194
    ],
    "[<space><a><n>]->[<o>]": [
      194
    ],
    "[<s><space><a><n>]->[<o>]": [
      194
    ],
    "[<i><s><space><a><n>]->[<o>]": [
      194
    ],
    "[<o>]->[<t>]": [
      127
    ],
    "[<n><o>]->[<t>]": [
      127
    ],
    "[<a><n><o>]->[<t>]": [
      127
    ],
    "[<space><a><n><o>]->[<t>]": [
      127
    ],
    "[<s><space><a><n><o>]->[<t>]": [
      127
    ],
    "[<o><t>]->[<h>]": [
      173
    ],
    "[<n><o><t>]->[<h>]": [
      173
    ],
    "[<a><n><o><t>]->[<h>]": [
      173
    ],
    "[<space><a><n><o><t>]->[<h>]": [
      173
    ],
    "[<h>]->[<e>]": [
      105
    ],
    "[<t><h>]->[<e>]": [
      105
    ],
    "[<o><t><h>]->[<e>]": [
      105
    ],
    "[<n><o><t><h>]->[<e>]": [
      105
    ],
    "[<a><n><o><t><h>]->[<e>]": [
      105
    ],
    "[<e>]->[<r>]": [
      162
    ],
    "[<h><e>]->[<r>]": [
      162
    ],
    "[<t><h><e>]->[<r>]": [
      162
    ],
    "[<o><t><h><e>]->[<r>]": [
      162
    ],
    "[<n><o><t><h><e>]->[<r>]": [
      162
    ],
    "[<r>]->[<space>]": [
      167
    ],
    "[<e><r>]->[<space>]": [
      167
    ],
    "[<h><e><r>]->[<space>]": [
      167
    ],
    "[<t><h><e><r>]->[<space>]": [
      167
    ],
    "[<o><t><h><e><r>]->[<space>]": [
      167
    ],
    "[<space>]->[<t>]": [
      196
    ],
    "[<r><space>]->[<t>]": [
      196
    ],
    "[<e><r><space>]->[<t>]": [
      196
    ],
    "[<h><e><r><space>]->[<t>]": [
      196
    ],
    "[<t><h><e><r><space>]->[<t>]": [
      196
    ],
    "[<t>]->[<e>]": [
      229
    ],
    "[<space><t>]->[<e>]": [
      229
    ],
    "[<r><space><t>]->[<e>]": [
      229
    ],
    "[<e><r><space><t>]->[<e>]": [
      229
    ],
    "[<h><e><r><space><t>]->[<e>]": [
      229
    ],
    "[<e>]->[<s>]": [
      200
    ],
    "[<t><e>]->[<s>]": [
      200
    ],
    "[<space><t><e>]->[<s>]": [
      200
    ],
    "[<r><space><t><e>]->[<s>]": [
      200
    ],
    "[<e><r><space><t><e>]->[<s>]": [
      200
    ],
    "[<e><s>]->[<space>]": [
      229
    ],
    "[<t><e><s>]->[<space>]": [
      229
    ],
    "[<space><t><e><s>]->[<space>]": [
      229
    ],
    "[<r><space><t><e><s>]->[<space>]": [
      229
    ],
    "[<space>]->[<backspace>]": [
      415
    ],
    "[<s><space>]->[<backspace>]": [
      415
    ],
    "[<e><s><space>]->[<backspace>]": [
      415
    ],
    "[<t><e><s><space>]->[<backspace>]": [
      415
    ],
    "[<space><t><e><s><space>]->[<backspace>]": [
      415
    ],
    "[<backspace>]->[<t>]": [
      170
    ],
    "[<space><backspace>]->[<t>]": [
      170
    ],
    "[<s><space><backspace>]->[<t>]": [
      170
    ],
    "[<e><s><space><backspace>]->[<t>]": [
      170
    ],
    "[<t><e><s><space><backspace>]->[<t>]": [
      170
    ],
    "[<t>]->[<space>]": [
      149,
      219
    ],
    "[<backspace><t>]->[<space>]": [
      149
    ],
    "[<space><backspace><t>]->[<space>]": [
      149
    ],
    "[<s><space><backspace><t>]->[<space>]": [
      149
    ],
    "[<e><s><space><backspace><t>]->[<space>]": [
      149
    ],
    "[<space>]->[<e>]": [
      223
    ],
    "[<t><space>]->[<e>]": [
      223
    ],
    "[<backspace><t><space>]->[<e>]": [
      223
    ],
    "[<space><backspace><t><space>]->[<e>]": [
      223
    ],
    "[<s><space><backspace><t><space>]->[<e>]": [
      223
    ],
    "[<e>]->[<n>]": [
      212,
      115
    ],
    "[<space><e>]->[<n>]": [
      212
    ],
    "[<t><space><e>]->[<n>]": [
      212
    ],
    "[<backspace><t><space><e>]->[<n>]": [
      212
    ],
    "[<space><backspace><t><space><e>]->[<n>]": [
      212
    ],
    "[<n>]->[<v>]": [
      234
    ],
    "[<e><n>]->[<v>]": [
      234
    ],
    "[<space><e><n>]->[<v>]": [
      234
    ],
    "[<t><space><e><n>]->[<v>]": [
      234
    ],
    "[<backspace><t><space><e><n>]->[<v>]": [
      234
    ],
    "[<v>]->[<i>]": [
      127
    ],
    "[<n><v>]->[<i>]": [
      127
    ],
    "[<e><n><v>]->[<i>]": [
      127
    ],
    "[<space><e><n><v>]->[<i>]": [
      127
    ],
    "[<t><space><e><n><v>]->[<i>]": [
      127
    ],
    "[<i>]->[<r>]": [
      167
    ],
    "[<v><i>]->[<r>]": [
      167
    ],
    "[<n><v><i>]->[<r>]": [
      167
    ],
    "[<e><n><v><i>]->[<r>]": [
      167
    ],
    "[<space><e><n><v><i>]->[<r>]": [
      167
    ],
    "[<r>]->[<o>]": [
      133
    ],
    "[<i><r>]->[<o>]": [
      133
    ],
    "[<v><i><r>]->[<o>]": [
      133
    ],
    "[<n><v><i><r>]->[<o>]": [
      133
    ],
    "[<e><n><v><i><r>]->[<o>]": [
      133
    ],
    "[<o>]->[<n>]": [
      221
    ],
    "[<r><o>]->[<n>]": [
      221
    ],
    "[<i><r><o>]->[<n>]": [
      221
    ],
    "[<v><i><r><o>]->[<n>]": [
      221
    ],
    "[<n><v><i><r><o>]->[<n>]": [
      221
    ],
    "[<n>]->[<m>]": [
      392
    ],
    "[<o><n>]->[<m>]": [
      392
    ],
    "[<r><o><n>]->[<m>]": [
      392
    ],
    "[<i><r><o><n>]->[<m>]": [
      392
    ],
    "[<v><i><r><o><n>]->[<m>]": [
      392
    ],
    "[<m>]->[<e>]": [
      144
    ],
    "[<n><m>]->[<e>]": [
      144
    ],
    "[<o><n><m>]->[<e>]": [
      144
    ],
    "[<r><o><n><m>]->[<e>]": [
      144
    ],
    "[<i><r><o><n><m>]->[<e>]": [
      144
    ],
    "[<m><e>]->[<n>]": [
      115
    ],
    "[<n><m><e>]->[<n>]": [
      115
    ],
    "[<o><n><m><e>]->[<n>]": [
      115
    ],
    "[<r><o><n><m><e>]->[<n>]": [
      115
    ],
    "[<n>]->[<t>]": [
      122
    ],
    "[<e><n>]->[<t>]": [
      122
    ],
    "[<m><e><n>]->[<t>]": [
      122
    ],
    "[<n><m><e><n>]->[<t>]": [
      122
    ],
    "[<o><n><m><e><n>]->[<t>]": [
      122
    ],
    "[<n><t>]->[<space>]": [
      219
    ],
    "[<e><n><t>]->[<space>]": [
      219
    ],
    "[<m><e><n><t>]->[<space>]": [
      219
    ],
    "[<n><m><e><n><t>]->[<space>]": [
      219
    ]
  }
}